# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 771ade20eab7b4a36759a26eb982040a65832df3b889b74b6bf8b81ea5059ef5467ac818afe418880652a1234736b019b59f7903514a237073e8abda42b8eb7a

test:
  secret_key_base: 27ac60dadc2536fe8b2befa7ab5a74ad4ca7625baf436ca0b3b206c1924dece6a4daf0547b8c47308e9ceac35ad129341f7da4ec1500a989aec87c6e8521d090

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
